### ISSUE TITLE
Pytorch version

### ISSUE THREAD

**Issue by nicehuster** [ZhiwenShao/JAANet#1]
what a wonderful project! I am eagerly  looking forward to the pytorch version of this project.

**Comment by ZhiwenShao** [comment]
Thanks! After the deadline of CVPR, I will finish the the pytorch version.

**Comment by BoyuanJiang** [comment]
@ZhiwenShao Hi， have you finished the pytorch version?

**Comment by ZhiwenShao** [comment]
I am very sorry for the delayed release of PyTorch version. The PyTorch implementation can be found [here](https://github.com/ZhiwenShao/PyTorch-JAANet)
