### ISSUE TITLE
DataTransformer has no member named 'mirror_crop_para_'

### ISSUE THREAD

**Issue by ttjack123** [ZhiwenShao/JAANet#3]
Thanks for your great work!  
However, I met a problem when compiling the modified caffe
It seems that the error comes from  src/caffe/layers/data_layer.cpp:134:84: error: ‘class caffe::DataTransformer<float>’ has no member named ‘mirror_crop_para_’
Can you give me some hint about this problem? 
Thanks a lot!

Here is my error log:
CXX src/caffe/layers/data_layer.cpp
CXX src/caffe/layers/input_layer.cpp
CXX src/caffe/layers/cudnn_sigmoid_layer.cpp
CXX src/caffe/layers/exp_layer.cpp
CXX src/caffe/layers/cudnn_lcn_layer.cpp
CXX src/caffe/layers/concat_layer.cpp
CXX src/caffe/layers/softmax_loss_layer.cpp
CXX src/caffe/layers/combination_layer.cpp
CXX src/caffe/layer.cpp
src/caffe/layers/data_layer.cpp: In instantiation of ‘void caffe::DataLayer<Dtype>::load_batch(caffe::Batch<Dtype>*) [with Dtype = float]’:
src/caffe/layers/data_layer.cpp:152:1:   required from here
src/caffe/layers/data_layer.cpp:134:84: error: ‘class caffe::DataTransformer<float>’ has no member named ‘mirror_crop_para_’
       top_label[item_id * 4 + para_id] = this->data_transformer_->mirror_crop_para_[item_id * 4 + para_id];
                                                                                    ^
src/caffe/layers/data_layer.cpp: In instantiation of ‘void caffe::DataLayer<Dtype>::load_batch(caffe::Batch<Dtype>*) [with Dtype = double]’:
src/caffe/layers/data_layer.cpp:152:1:   required from here
src/caffe/layers/data_layer.cpp:134:84: error: ‘class caffe::DataTransformer<double>’ has no member named ‘mirror_crop_para_’
Makefile:591: recipe for target '.build_release/src/caffe/layers/data_layer.o' failed
make: *** [.build_release/src/caffe/layers/data_layer.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by ZhiwenShao** [comment]
Sorry, I forgot to add the definition of DataParameter into caffe.proto. Please refer to the new caffe.proto file, in which the following line corresponds to mirror_crop_para_:
optional bool get_mirror_crop = 11 [default = false];

**Comment by ZhiwenShao** [comment]
Also, you need to update the data_transformer.cpp and data_transformer.hpp, which have been uploaded to src and include. If there are still some errors, since there could be differences among different caffe versions, you'd better merge the code related to mirror_crop into the data_transformer.cpp and data_transformer.hpp of the new caffe version files.

**Comment by ttjack123** [comment]
It works, thanks!
