### ISSUE TITLE
Format of the input data

### ISSUE THREAD

**Issue by ttjack123** [ZhiwenShao/JAANet#4]
Hi, Zhiwen Shao, sorry to bother you again.  
I have some confusions when preparing the lmdb input data: 
As shown in model/BP4D_train_val.prototxt, the network takes 6 lmdb inputs
1. BP4D_combine_1_2_ldb
2. BP4D_combine_1_2_AUoccur_ldb
3. BP4D_combine_1_2_land_ldb
4. BP4D_combine_1_2_biocular_ldb
5. reflect_49_ldb
6. BP4D_combine_1_2_weight_ldb

I know the first one is image, the second one is AU label and the third one is landmark points,  but there are questions: 
A.  What's the format and data type of  BP4D_combine_1_2_AUoccur_ldb ? 
     I think it is a N*12  bool matrix, am I right?  Besides, since in BP4D there may exist labels equal to 9 which refers the AU occurrence is unknown, how do you process these labels?

B.  What's the format and data type of  BP4D_combine_1_2_land_ldb? 
      I run prep/face_transform.cpp and it generate a  BP4D_output_land.txt.  Does the BP4D_combine_1_2_land_ldb equals to the values of BP4D_output_land.txt? Besides, I notice the points in BP4D_output_land.txt are separated by '\t' in each line, how can I transform this kind of lines to lmdb?

		for (int r = 0; r < ptsMat_3d.rows; r++)
		{
			for (int c = 0; c < 2; c++)
			{
				output_land << ptsMat_3d.at<float>(r, c) << '\t';
			}
		}
		output_land << "\n";

C.  What does   BP4D_combine_1_2_biocular_ldb,  reflect_49_ldb,  and  BP4D_combine_1_2_weight_ldb mean? How can I generate them?

Looking forward to your reply, thank you!

**Comment by ZhiwenShao** [comment]
(1) The example format of files for AU and landmark labels, inter-ocular distances and weights are in "data/examples"; reflect_49.txt is in "data"; the weights are shared by all the training samples (only one line needed); reflect_49 is used to reset the order and change the coordinates for landmarks in the case of face mirroring. You can use the tools/convert_data to convert the text files to lmdb.
(2) Our method is evaluated by 3-fold cross validation. For example, “BP4D_combine_1_2” denotes the combination of partition 1 and partition 2.
(3)  You need to replace the '\t' with ' ' (via a text editor), and I have updated the face_transform.cpp. BP4D_output_land.txt is the processed landmark labels to be used for training.
(4) The annotations of evaluated 12 AUs for BP4D don't contain missing labels.
See ReadMe for more details.

**Comment by ttjack123** [comment]
Thanks! I will try.
