### ISSUE TITLE
caffe cannot build

### ISSUE THREAD

**Issue by yehongshen** [ZhiwenShao/JAANet#6]
after i merged "src" and "include" into the official Caffe, i try to build the caffe ,i meet this problem :

caffe.proto:330:12: "AlignDataTransformParameter" is not defined.
make: *** [.build_release/src/caffe/proto/caffe.pb.cc] Error 1

how should i define the "AlignDataTransformParameter"

**Comment by ZhiwenShao** [comment]
You need to merge the content in src/caffe.proto to official caffe.proto

**Comment by yehongshen** [comment]
thanks for your reply. yes , i have merged the content in src/caffe.proto to official caffe.proto, but in your caffe.proto , i could not find the defination of AlignDataTransformParameter.

**Comment by ZhiwenShao** [comment]
message LayerParameter {
	optional AUMaskBasedLandParameter au_mask_based_land_param = 1;
	optional DivisionParameter division_param = 2;
	optional CombinationParameter combination_param = 3;
	optional AlignDataTransformParameter align_data_transform_param = 4;
	optional DiceCoefLossParameter dice_coef_loss_param = 5;
}

No variable needs to be defined for AlignDataTransformParameter.

**Comment by yehongshen** [comment]
@ZhiwenShao Thanks for your help, but maybe i merged the content in a wrong way, so i post the error message i encounted, and the caffe.proto after i merged 
![图片](https://user-images.githubusercontent.com/29135906/55390317-8dc5fa80-5569-11e9-8436-11f16f720b3f.png)
![图片](https://user-images.githubusercontent.com/29135906/55390663-42601c00-556a-11e9-9143-1eea5a50278d.png)

**Comment by yehongshen** [comment]
@ZhiwenShao So can you help me figure out what I'm doing wrong

**Comment by sweetheart123** [comment]
@ZhiwenShao  i am also facing same problem. can you help ?

**Comment by ZhiwenShao** [comment]
You can not directly copy the content in my caffe.proto to the official caffe.proto. You should keep the original official caffe.proto by introducing the new defined layers. That is to say, you may define  "optional AUMaskBasedLandParameter au_mask_based_land_param =  120; (119 is the last used number in the official caffe.proto)"

**Comment by yehongshen** [comment]
@ZhiwenShao I'll try. thank you so much,

**Comment by sweetheart123** [comment]
@ZhiwenShao  lets try. Thank you very much

**Comment by kushagramahajan** [comment]
@ZhiwenShao  I am still facing the issue with the "AlignDataTransformParameter" variable since there is no definition for "AlignDataTransformParameter" either in your caffe.proto or the original caffe.proto
