### ISSUE TITLE
how to visualize attention maps

### ISSUE THREAD

**Issue by lilaczhou** [ZhiwenShao/JAANet#7]
![image](https://user-images.githubusercontent.com/45725450/67349126-a33c5980-f579-11e9-83d4-7f5f3ce6a316.png)
Does anyone have ideas how to visualize the attention maps?

**Comment by ZhiwenShao** [comment]
Sorry for late reply. I have uploaded visualize_attention_map.py to "model/".

**Comment by lilaczhou** [comment]
Thank you a lot!
