### ISSUE TITLE
caffemodel

### ISSUE THREAD

**Issue by yy19931029** [ZhiwenShao/JAANet#8]
hello, do you have the model:  AUNet_iter_?0000.caffemodel?

**Comment by ZhiwenShao** [comment]
Trained models on BP4D with 3-fold cross-validation can be downloaded [here](https://sjtueducn-my.sharepoint.com/:f:/g/personal/shaozhiwen_sjtu_edu_cn/EhVWf3EgvnNLj-o_fWT3InEBCcI9vlnxkrOkSOUxRAzkAg?e=XN9v67)

**Comment by yy19931029** [comment]
非常感谢！

**Comment by yy19931029** [comment]
Forgive me a new bird in caffe, your model I download now, but I still have two questions to ask, the first one is that your model have 3 parts, is it just different from train data between them. I saw in your "test.py", the model name is AUNet_iter_?0000.caffemodel, is it the model that I downloaded? Thank you again.

**Comment by ZhiwenShao** [comment]
The test.py evaluates all saved models including intermediate models, but the released model are final models for 3-fold cross-validation.

**Comment by yy19931029** [comment]
So if I want to use the final model, I need to train myself?

**Comment by yy19931029** [comment]
Another question is that when I use python to test, my vscode said that there was no field named"division_param" in "caffe.LayerParameter", is it the layer defined by you? If I want to use in python, what should I do? Thank you!

**Comment by yy19931029** [comment]
hello, sorry to trouble you again, I built caffe success after add all your cpp、hpp and cu. But when I use python to run "test.py", it showed that "layer_factory.hpp:81] Check failed: registry.count(type) == 1 (0 vs. 1) Unknown layer type: Division", did you meet this question when you use caffe in python?

**Comment by yy19931029** [comment]
hello, I add the layer follow you github in caffe and rebuild caffe success, but it show me "Check failed: status == CUDNN_STATUS_SUCCESS (1 vs. 0)  CUDNN_STATUS_NOT_INITIALIZED". Have you meet this problem?

**Comment by yy19931029** [comment]
Hello, I solved problem I ask last time, my gpu is not enough so I use cpu to do that, I test your model, but the 49 point landmark seem not chang when my face move, did you use it on your own face to check it?

**Comment by yy19931029** [comment]
Hello, do you have the file "visualize_attention_map.py", I didn't find in your code, Thank you!
