### ISSUE TITLE
How do the attention maps utilize landmarks?

### ISSUE THREAD

**Issue by lilaczhou** [ZhiwenShao/JAANet#9]
@ZhiwenShao Hello，after reading codes，I donot understand how you utilize predicted landmarks to generate attention maps.In my understanding,landmarks are used to judge whether the attention maps' areas  are in the range of images,could you tell me whether I am right?
Maybe you could tell me more about how to combine attention maps and landmarks,thank you a lot!

**Comment by lilaczhou** [comment]
Would you please give me some hint？

**Comment by ZhiwenShao** [comment]
Each AU has two centers predefined by two landmarks. Then, two ROIs with predefined width around the centers can be obtained, in which a position with a farther Manhattan distance to the AU center has a lower attention. For positions beyond the ROIs, the attention weights are zero. For details, please read the paper.
